-- ============================================================
-- DÉBORA APARECIDA NAIL DESIGN
-- CONFIGURAÇÃO COMPLETA DO SUPABASE
-- ============================================================

-- ------------------------------------------------------------
-- 1. CLIENTES
-- ------------------------------------------------------------

alter table public.clientes
add column if not exists is_admin boolean default false;

alter table public.clientes
alter column id add generated by default as identity;

alter table public.clientes
drop constraint if exists clientes_user_id_fkey;

alter table public.clientes
add constraint clientes_user_id_fkey
foreign key (user_id)
references auth.users(id)
on delete cascade;

create unique index if not exists clientes_email_unique
on public.clientes (lower(email));

create unique index if not exists clientes_user_id_unique
on public.clientes (user_id);


-- ------------------------------------------------------------
-- 2. HORÁRIOS
-- ------------------------------------------------------------

create unique index if not exists horarios_data_horario_unique
on public.horarios (data, horario);


-- ------------------------------------------------------------
-- 3. AGENDAMENTOS
-- ------------------------------------------------------------

create unique index if not exists agendamentos_data_horario_unique
on public.agendamentos (data, horario);


-- ------------------------------------------------------------
-- 4. VIP
-- ------------------------------------------------------------

create unique index if not exists vip_cliente_unique
on public.vip_fidelidade (cliente_id);


-- ------------------------------------------------------------
-- 5. FUNÇÃO PARA SABER SE O USUÁRIO É ADMIN
-- ------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.clientes
    where user_id = auth.uid()
      and is_admin = true
  );
$$;


-- ------------------------------------------------------------
-- 6. FUNÇÃO PARA SABER SE O CLIENTE É DONO DO CADASTRO
-- ------------------------------------------------------------

create or replace function public.owns_client(client_id bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.clientes
    where id = client_id
      and user_id = auth.uid()
  );
$$;


-- ------------------------------------------------------------
-- 7. ATIVAR RLS
-- ------------------------------------------------------------

alter table public.clientes enable row level security;
alter table public.agendamentos enable row level security;
alter table public.vip_fidelidade enable row level security;
alter table public.horarios enable row level security;


-- ------------------------------------------------------------
-- 8. REMOVER POLÍTICAS ANTIGAS
-- ------------------------------------------------------------

drop policy if exists "clientes_select_own" on public.clientes;
drop policy if exists "clientes_insert_own" on public.clientes;
drop policy if exists "clientes_update_own" on public.clientes;
drop policy if exists "clientes_admin_all" on public.clientes;

drop policy if exists "agendamentos_select_own" on public.agendamentos;
drop policy if exists "agendamentos_insert_own" on public.agendamentos;
drop policy if exists "agendamentos_admin_all" on public.agendamentos;

drop policy if exists "vip_select_own" on public.vip_fidelidade;
drop policy if exists "vip_admin_all" on public.vip_fidelidade;

drop policy if exists "horarios_select_available" on public.horarios;
drop policy if exists "horarios_admin_all" on public.horarios;


-- ============================================================
-- 9. POLÍTICAS — CLIENTES
-- ============================================================

create policy "clientes_select_own"
on public.clientes
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin()
);

create policy "clientes_insert_own"
on public.clientes
for insert
to authenticated
with check (
  user_id = auth.uid()
);

create policy "clientes_update_own"
on public.clientes
for update
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin()
)
with check (
  user_id = auth.uid()
  or public.is_admin()
);

create policy "clientes_admin_all"
on public.clientes
for all
to authenticated
using (
  public.is_admin()
)
with check (
  public.is_admin()
);


-- ============================================================
-- 10. POLÍTICAS — AGENDAMENTOS
-- ============================================================

create policy "agendamentos_select_own"
on public.agendamentos
for select
to authenticated
using (
  public.owns_client(cliente_id)
  or public.is_admin()
);

create policy "agendamentos_insert_own"
on public.agendamentos
for insert
to authenticated
with check (
  public.owns_client(cliente_id)
);

create policy "agendamentos_admin_all"
on public.agendamentos
for all
to authenticated
using (
  public.is_admin()
)
with check (
  public.is_admin()
);


-- ============================================================
-- 11. POLÍTICAS — VIP
-- ============================================================

create policy "vip_select_own"
on public.vip_fidelidade
for select
to authenticated
using (
  public.owns_client(cliente_id)
  or public.is_admin()
);

create policy "vip_admin_all"
on public.vip_fidelidade
for all
to authenticated
using (
  public.is_admin()
)
with check (
  public.is_admin()
);


-- ============================================================
-- 12. POLÍTICAS — HORÁRIOS
-- ============================================================

create policy "horarios_select_available"
on public.horarios
for select
to authenticated
using (
  disponivel = true
  or public.is_admin()
);

create policy "horarios_admin_all"
on public.horarios
for all
to authenticated
using (
  public.is_admin()
)
with check (
  public.is_admin()
);


-- ============================================================
-- FIM DA CONFIGURAÇÃO
-- ============================================================
